"use client";

import { useState, useRef } from "react";
import { Button } from "@/components/ui/button";
import { ExportedDream } from "@/lib/schemas";
import { UploadCloud, Activity, Trash2 } from "lucide-react";
import { Header } from "@/components/header";
import { useI18n } from "@/components/i18n-provider";

export default function ArchivePage() {
  const { lang, t } = useI18n();
  const [dreams, setDreams] = useState<ExportedDream[]>([]);
  const [compareReport, setCompareReport] = useState<any>(null);
  const [isComparing, setIsComparing] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files) return;

    Array.from(files).forEach((file) => {
      const reader = new FileReader();
      reader.onload = (event) => {
        try {
          const json = JSON.parse(event.target?.result as string);
          // Assuming basic validation
          if (json.version && json.input && json.report) {
             setDreams(prev => {
                // Avoid duplicates by timestamp or title
                if (prev.some(d => d.timestamp === json.timestamp)) return prev;
                return [...prev, json].sort((a, b) => new Date(b.input.date).getTime() - new Date(a.input.date).getTime());
             });
          }
        } catch (error) {
          console.error("Invalid file format");
          alert(lang === "en" ? "Invalid file format. Please select JSON files generated by this system." : "檔案格式不符，請選擇透過系統下載的夢境 JSON 檔案。");
        }
      };
      reader.readAsText(file);
    });

    if (fileInputRef.current) {
        fileInputRef.current.value = "";
    }
  };

  const removeDream = (timestamp: string) => {
    setDreams(prev => prev.filter(d => d.timestamp !== timestamp));
    setCompareReport(null);
  };

  const runComparison = async () => {
    if (dreams.length < 2) return;
    
    setIsComparing(true);
    try {
      const payload = dreams.map(d => ({
         date: d.input.date,
         title: d.input.title,
         wakingEmotion: d.input.wakingEmotion,
         dreamEmotion: d.input.dreamEmotion,
         theme: d.report.summary.theme,
         mainSymbols: d.report.summary.mainSymbols
      }));

      const headers: Record<string, string> = { 
        "Content-Type": "application/json",
        "x-app-lang": lang
      };

      const res = await fetch("/api/compare", {
        method: "POST",
        headers,
        body: JSON.stringify(payload),
      });

      if (res.status === 413) {
         alert(lang === "en" ? "Input too large. Please shorten your dream content before comparing." : "輸入字數過多，伺服器無法處理，請縮減比較內容。");
         return;
      }

      if (res.status === 504) {
         alert(lang === "en" ? "Server timeout (504). The comparison took too long. Please try selecting fewer items to compare." : "伺服器超時 (504)，比較過程花費了太長時間。由於伺服器有處理時間限制，請嘗試減少比較的夢境數量後再試一次。");
         return;
      }

      if (res.status === 503) {
         alert(lang === "en" ? "The AI service is currently experiencing high demand. Please try again later." : "AI 服務器目前正處於高負載狀態，請稍後再試。");
         return;
      }

      let result;
      try {
        result = await res.json();
      } catch (parseError) {
        throw new Error("Invalid response from server: " + res.status);
      }

      if (res.status === 400 && result.error === "Invalid prompt content detected.") {
         alert(lang === "en" ? "Invalid characters or restricted keywords detected." : "檢測到無效字元或嘗試繞過系統的指令，拒絕請求。");
         return;
      }

      if (result.type === "SUCCESS") {
         setCompareReport(result.report);
      } else {
         alert(lang === "en" ? "Comparison failed, please try again." : "比較失敗，請稍後再試。");
      }
    } catch (error) {
      alert(lang === "en" ? "Network connection failed or input data is too large." : "網路連線失敗，或輸入資料超出上限。");
    } finally {
      setIsComparing(false);
    }
  };

  return (
    <main className="min-h-screen bg-stone-50 pb-20 selection:bg-stone-200 text-stone-900">
      <div className="bg-white border-b border-stone-200 shadow-sm relative pt-4 pb-2 px-4 mb-10">
        <div className="max-w-5xl mx-auto">
          <Header />
        </div>
      </div>

      <div className="max-w-5xl mx-auto px-4 animate-in fade-in fill-mode-both duration-500">
         
         <div className="bg-white p-8 rounded-xl border border-stone-200 shadow-sm text-center">
            <input 
              type="file" 
              multiple 
              accept=".json" 
              className="hidden" 
              ref={fileInputRef} 
              onChange={handleFileUpload}
            />
            <div className="h-12 w-12 bg-stone-50 border border-stone-200 rounded-full flex items-center justify-center mx-auto mb-4 text-stone-500">
               <UploadCloud className="h-6 w-6" />
            </div>
            <h2 className="text-xl font-bold text-stone-900 mb-2">{t("archive_title")}</h2>
            <p className="text-sm text-stone-500 max-w-md mx-auto mb-6 leading-relaxed">
              {t("archive_desc")}
            </p>
            <Button onClick={() => fileInputRef.current?.click()}>
              {t("archive_upload_btn")}
            </Button>
         </div>

         {dreams.length > 0 && (
            <div className="space-y-4 mt-8">
                <div className="flex items-center justify-between">
                   <h3 className="text-lg font-bold text-stone-900">{t("archive_uploaded_list")} ({dreams.length})</h3>
                   <Button 
                      variant="secondary" 
                      onClick={runComparison}
                      disabled={dreams.length < 2 || isComparing}
                   >
                     {isComparing ? (
                         <>
                            <div className="h-4 w-4 mr-2 rounded-full border-2 border-stone-900 border-t-transparent animate-spin"></div>
                            {t("archive_comparing")}
                         </>
                     ) : (
                         <><Activity className="h-4 w-4 mr-2" /> {t("archive_compare_btn")}</>
                     )}
                   </Button>
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                   {dreams.map(dream => (
                      <div key={dream.timestamp} className="bg-white p-4 rounded-xl border border-stone-200 shadow-sm relative group">
                         <button 
                           onClick={() => removeDream(dream.timestamp)}
                           className="absolute top-3 right-3 text-stone-400 hover:text-red-500 transition-colors opacity-0 group-hover:opacity-100"
                         >
                            <Trash2 className="h-4 w-4" />
                         </button>
                         <h4 className="font-medium text-stone-900 pr-6 truncate">{dream.input.title}</h4>
                         <p className="text-xs text-stone-500 mb-3">{dream.input.date}</p>
                         <div className="text-sm text-stone-600 line-clamp-2">
                             {dream.input.dreamContent}
                         </div>
                      </div>
                   ))}
                </div>
            </div>
         )}
         
         {dreams.length > 0 && dreams.length < 2 && (
             <p className="text-sm text-stone-500 text-center py-4 mt-8">
                 {lang === "en" ? "Please import at least 2 dream records to enable comparison." : "請匯入至少 2 筆以上的夢境紀錄以啟用比較功能。"}
             </p>
         )}

         {compareReport && (
            <div className="mt-8 space-y-6">
                <h2 className="text-2xl font-bold text-stone-900">{t("archive_report_title")}</h2>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                   <div className="space-y-4 border border-stone-200 rounded-xl p-5 bg-white shadow-sm">
                      <h4 className="font-bold text-stone-900 border-b border-stone-100 pb-2">{t("archive_pattern_title")}</h4>
                      <ul className="list-disc list-inside text-sm text-stone-600 space-y-1">
                          {compareReport.recurringSymbols.map((item: string, i: number) => <li key={i}>{item}</li>)}
                          {compareReport.recurringSymbols.length === 0 && <li>{lang === "en" ? "No clear recurring symbols" : "無明顯重複象徵"}</li>}
                      </ul>
                   </div>
                   <div className="space-y-4 border border-stone-200 rounded-xl p-5 bg-white shadow-sm">
                      <h4 className="font-bold text-stone-900 border-b border-stone-100 pb-2">{t("archive_trend_title")}</h4>
                      <ul className="list-disc list-inside text-sm text-stone-600 space-y-1">
                          {compareReport.recurringEmotions.map((item: string, i: number) => <li key={i}>{item}</li>)}
                          {compareReport.recurringEmotions.length === 0 && <li>{lang === "en" ? "No clear emotional consistency" : "無明顯情感一致性"}</li>}
                      </ul>
                   </div>
                   <div className="space-y-4 border border-stone-200 rounded-xl p-5 bg-white shadow-sm">
                      <h4 className="font-bold text-stone-900 border-b border-stone-100 pb-2">反覆出現的主題</h4>
                      <ul className="list-disc list-inside text-sm text-stone-600 space-y-1">
                          {compareReport.commonThemes.map((item: string, i: number) => <li key={i}>{item}</li>)}
                          {compareReport.commonThemes.length === 0 && <li>{lang === "en" ? "No recurring theme" : "無明顯雷同主題"}</li>}
                      </ul>
                   </div>
                </div>

                <div className="border border-stone-200 rounded-xl p-6 bg-white shadow-sm space-y-3">
                   <h4 className="text-lg font-bold text-stone-900">{t("archive_timeline_title")}</h4>
                   <p className="text-base text-stone-700 leading-relaxed">
                       {compareReport.timelineAnalysis}
                   </p>
                </div>
            </div>
         )}
      </div>
    </main>
  );
}
